# Generated by Django 2.1.3 on 2018-11-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20181130_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=5000),
        ),
    ]
