# Generated by Django 2.1.3 on 2018-12-17 22:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20181130_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_mes', models.CharField(max_length=300)),
                ('name_man', models.CharField(max_length=50)),
                ('date_answer', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_razdel', models.IntegerField(default=0)),
                ('name_theme', models.CharField(max_length=200)),
                ('name_creator', models.CharField(max_length=50)),
                ('name_last_answer', models.CharField(max_length=200)),
                ('date_last_answer', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='id_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto.Topic'),
        ),
    ]
